services:
  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile.prod
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docker_network
    env_file:
      - ./mysql/.env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "9000:80"
    networks:
      - docker_network

  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile.prod
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./next:/app
    networks:
      - docker_network

  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8080"
    depends_on:
      - db
    networks:
      - docker_network
    environment:
      PYTHONPATH: /app

volumes:
  mysql_data:

networks:
  docker_network:
    external: true